name: Makefile CI

on:
  push:
    branches:
      - main
      - add-ci
  pull_request:
  workflow_dispatch:

env:
  GOLANG_VERSION: 1.23

jobs:
  constants: 
    runs-on: ubuntu-latest
    outputs:
      golang_version: ${{ steps.set_constants.outputs.golang_version }}
    steps:
    - id: set_constants
      run: echo "golang_version=${{ env.GOLANG_VERSION }}" >> $GITHUB_OUTPUT

  test:
    runs-on: ubuntu-latest
    needs: constants
    container:
      image: golang:${{ needs.constants.outputs.golang_version }}
    steps:
    - uses: actions/checkout@v4
    - name: Run test
      run: make test

  build:
    runs-on: ubuntu-latest
    needs:
      - constants
      - test
    strategy:
      matrix:
        arch: [amd64, arm64]
    container:
      image: golang:${{ needs.constants.outputs.golang_version }}
      env:
        GOARCH: ${{ matrix.arch }}
    steps:
    - uses: actions/checkout@v4
    - name: Run build
      run: make build
    - name: Upload
      uses: actions/upload-artifact@v4
      with:
        name: bin-${{ matrix.arch }}
        path: build/*
